### ISSUE TITLE
Schematic - wrong connection of motor

### ISSUE THREAD

**Issue by networxnet** [romanseidl/MillControl#1]
As i can see there is some mistake in the schematic. I think motor should be connected to phase instead of ground, cause relay C is connected to ground.
Please check.

**Comment by romanseidl** [comment]
Thanks for noticing. You are right this is wrong. :)

I'll fix it when I get to it. 

The Readme is a bit out of date, if you can read german you can find a more up to date version here:
http://www.kaffee-netz.de/threads/millcontrol-arduino-muehlensteuerung-mit-timer-gewichtsautomatik-und-brew-timer.95553/

Are you planning on using the code?

**Comment by romanseidl** [comment]
I produced a new schematic, that fixed the bug. Thanks again for mentioning.
